Fix public_fused_types tests.
This breaks fused_def tests due C compiler warning (example not relatedt o fused_def test):

fused_def.cpp:57810:56: error: assigning to 'double (*)(struct __pyx_obj_9fused_def_A *, double)' from incompatible type 'double (*)(struct __pyx_obj_9fused_def_B *, double)': type mismatch at 1st parameter ('struct __pyx_obj_9fused_def_A *' vs 'struct __pyx_obj_9fused_def_B *')
  __pyx_vtable_9fused_def_B.__pyx_base.__pyx_fuse_0f = (double (*)(struct __pyx_obj_9fused_def_B *, double))__pyx_fuse_0__pyx_f_9fused_def_1B_f;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fused_def.cpp:57811:56: error: assigning to 'int (*)(struct __pyx_obj_9fused_def_A *, int)' from incompatible type 'int (*)(struct __pyx_obj_9fused_def_B *, int)': type mismatch at 1st parameter ('struct __pyx_obj_9fused_def_A *' vs 'struct __pyx_obj_9fused_def_B *')
  __pyx_vtable_9fused_def_B.__pyx_base.__pyx_fuse_1f = (int (*)(struct __pyx_obj_9fused_def_B *, int))__pyx_fuse_1__pyx_f_9fused_def_1B_f;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~