Support 2 and 3 arg __[ri]pow__ (#5168)
This change accepts both two and three argument versions
for `__pow__` and `__ipow__`.

For the two arg versions it raises an exception if three
arguments are passed (although accepts a third argument of
'None' since this is what Python does by default).

For the three arg versions it allows a default argument of None
to be set (but no other default arguments).

One deviation from Python:

```
class C:
  def __pow__(a, b, c):
    return a, b, c
```

will raise `TypeError: C.__pow__() missing 1 required positional
argument: 'c'`
for all of
```
C()**2
pow(C(), 2)
pow(C(), 2, None)
```

(i.e. it just looks to see if None has been passed and treats
that are 2 args only).

I haven't done this - it seems like a backwards compatibility
mistake for Cython. Although it would be possible.

I haven't tied any of this to `c_api_binop_methods`. I think it's
independent, although if we did want to reject None on the three
argument power function, we could use that directive.