Fix cython build rules not accounting for cython-version-platform in so name
Running these rules on a RBE on linux produces the following shared object file:

`frontend.cpython-38-x86_64-linux-gnu.so`

The `cpython-38-x86_64-linux-gnu` modifier means that the build rule cannot find this file and fails like so:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 2] No such file or directory
```

This rule is quite hard to decipher so break out the one line script into one that can send explicit errors to the user, and handle cases where the cython version file name modifier was added.