Add missing ufunc decorator to type annotations (#7136)
- Add ufunc to the decorator assignment in Shadow.pyi
- Fixes mypy error: Module has no attribute 'ufunc'
- Resolves issue where @cython.ufunc was not recognized by type checkers
https://github.com/cython/cython/issues/7109